services:
  - type: static
    name: ignivance-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: redirect
        source: /ads.txt
        destination: https://srv.adstxtmanager.com/19390/ignivance.in
      - type: rewrite
        source: /*
        destination: /index.html